apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wolfshop-nfs-pvc
  namespace: wolfshop
spec:
  storageClassName: nfs-static
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
