apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: wolfshop-gateway
  namespace: wolfshop
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.wolfshop.com"
